import { unzipSync, type Unzipped } from "fflate";
import { access, mkdir, chmod, cp, readFile, rm, writeFile } from "node:fs/promises";
import { join, resolve, sep, dirname } from "node:path";

/** Extract a starter.zip buffer into the target directory. */
export async function unzipToDir(zip: ArrayBuffer, targetDir: string): Promise<number> {
  const files: Unzipped = unzipSync(new Uint8Array(zip));
  const root = resolve(targetDir);

  const paths = Object.keys(files);
  for (const path of paths) {
    if (path.endsWith("/")) continue; // directory entries
    const parts = path.split("/");
    // Basic zip-slip protection: reject paths escaping the target dir.
    const dest = resolve(root, ...parts);
    if (dest !== root && !dest.startsWith(root + sep)) {
      throw new Error(`Illegal path in archive: ${path}`);
    }
    const data = files[path]!;
    await mkdir(dest.substring(0, dest.lastIndexOf(sep)), { recursive: true });
    await writeFile(dest, data);
  }

  // Make Maven/Gradle wrappers executable (zip modes are not preserved by fflate).
  for (const wrapper of ["mvnw", "gradlew"]) {
    try {
      await chmod(join(root, wrapper), 0o755);
    } catch {
      // wrapper not present in this project
    }
  }
  return paths.filter((p) => !p.endsWith("/")).length;
}

async function exists(path: string): Promise<boolean> {
  try {
    await access(path);
    return true;
  } catch {
    return false;
  }
}

/** Write a text file, creating parent directories as needed. */
export async function writeTextFile(path: string, content: string): Promise<void> {
  await mkdir(dirname(path), { recursive: true });
  await writeFile(path, content);
}

/** Read a UTF-8 file, or return null when it does not exist. */
export async function readTextFileIfExists(path: string): Promise<string | null> {
  try {
    return await readFile(path, "utf8");
  } catch {
    return null;
  }
}

/**
 * Copy `relPath` from `fromDir` to `toDir` when it exists, recursing into
 * directories.
 *
 * A monorepo has exactly one wrapper and one set of shared dotfiles, at the
 * root; every module generated by Initializr ships its own copy, so the first
 * module's is hoisted rather than synthesised.
 */
export async function hoistIfPresent(
  fromDir: string,
  toDir: string,
  relPath: string,
): Promise<boolean> {
  const src = join(fromDir, relPath);
  if (!(await exists(src))) return false;
  const dest = join(toDir, relPath);
  await mkdir(dirname(dest), { recursive: true });
  // copyFile cannot handle directories such as .mvn/ or gradle/wrapper/.
  await cp(src, dest, { recursive: true, force: true });
  return true;
}

/** Delete a file or directory if present. */
export async function removeIfPresent(path: string): Promise<void> {
  await rm(path, { recursive: true, force: true });
}

/** Make a wrapper script executable after it has been copied to a new location. */
export async function ensureExecutable(path: string): Promise<void> {
  if (await exists(path)) {
    await chmod(path, 0o755);
  }
}
